"""Rule table: one entry per Jenkins construct the analyzer knows about.

Each rule is a compiled regex applied line by line to a comment-stripped Jenkinsfile. Rules are
deliberately simple pattern matches. A Jenkinsfile is Groovy, and a real parser would be a large
dependency for a tool whose job is to produce a checklist a human reads; every construct here has
a distinctive keyword that a regex catches reliably.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from migration_analyzer.model import Category


@dataclass(frozen=True)
class Rule:
    id: str
    pattern: re.Pattern[str]
    category: Category
    title: str
    actions_equivalent: str
    note: str = ""
    once: bool = False  # report only the first match


def _r(
    id: str,
    pattern: str,
    category: Category,
    title: str,
    equivalent: str,
    note: str = "",
    once: bool = False,
) -> Rule:
    return Rule(id, re.compile(pattern), category, title, equivalent, note, once)


RULES: list[Rule] = [
    # --- structure --------------------------------------------------------------------------------
    _r(
        "shared-library",
        r"@Library\s*\(",
        Category.MANUAL,
        "Shared library import",
        "Composite actions (.github/actions/*) for vars/ steps; reusable workflows for whole "
        "pipelines. Classes under src/ have no equivalent.",
        "Port the library first; everything else depends on it.",
        once=True,
    ),
    _r(
        "agent-docker",
        r"\bagent\s*\{\s*docker\b|^\s*docker(file)?\s*\{",
        Category.REVIEW,
        "Docker agent",
        "actions/setup-* for toolchains, or `container:` on the job to run inside the image.",
        "Prefer setup actions; `container:` jobs cannot use some actions that need the host.",
        once=True,
    ),
    _r(
        "docker-socket",
        r"/var/run/docker\.sock",
        Category.MANUAL,
        "Docker socket mounted into the agent",
        "None. GitHub-hosted runners have Docker available without a socket mount.",
        "Check what the socket was for; image builds work as-is, DinD sidecars need redesign.",
    ),
    _r(
        "agent-label",
        r"\blabel\s+['\"][^'\"]+['\"]",
        Category.REVIEW,
        "Agent label selector",
        "`runs-on:` with a hosted runner label or self-hosted runner labels.",
        "Map each Jenkins label to a runner label; there is no boolean label expression syntax.",
    ),
    _r(
        "stage",
        r"\bstage\s*\(\s*['\"]([^'\"]+)['\"]\s*\)",
        Category.AUTO,
        "Stage",
        "A job (or a step within a job, for cheap sequential stages).",
    ),
    _r(
        "parallel",
        r"\bparallel\s*\{",
        Category.AUTO,
        "Parallel stages",
        "Separate jobs with no `needs` edge between them.",
    ),
    _r(
        "matrix",
        r"\bmatrix\s*\{",
        Category.AUTO,
        "Matrix",
        "`strategy.matrix` on the job.",
    ),
    _r(
        "script-block",
        r"\bscript\s*\{",
        Category.REVIEW,
        "Scripted Groovy block",
        "Shell `run:` steps, or a small script checked into the repo.",
        "Groovy logic must be rewritten; look at what the block computes and where it is used.",
    ),
    # --- parameters, env, triggers ------------------------------------------------------------
    _r(
        "parameters",
        r"\bparameters\s*\{",
        Category.AUTO,
        "Build parameters",
        "`workflow_dispatch.inputs` (choice, boolean, string types all exist).",
        once=True,
    ),
    _r(
        "environment-block",
        r"\benvironment\s*\{",
        Category.AUTO,
        "Environment block",
        "`env:` at workflow, job or step level.",
        "Entries that call credentials() are reported separately.",
        once=True,
    ),
    _r(
        "credentials-helper",
        r"\bcredentials\s*\(\s*['\"]([^'\"]+)['\"]\s*\)",
        Category.REVIEW,
        "credentials() binding",
        "`${{ secrets.<NAME> }}` after creating the secret in the right scope.",
        "Username/password credentials expand to two variables in Jenkins (_USR/_PSW); "
        "create two secrets or use a single token.",
    ),
    _r(
        "with-credentials",
        r"\bwithCredentials\s*\(",
        Category.REVIEW,
        "withCredentials block",
        "Step-level `env:` mapping `${{ secrets.NAME }}` to the variable the script expects.",
        "File credentials become base64 secrets written to $RUNNER_TEMP; "
        "prefer OIDC for cloud providers.",
    ),
    _r(
        "credentials-id",
        r"credentialsId\s*:\s*['\"]([^'\"]+)['\"]",
        Category.REVIEW,
        "Credential ID",
        "A repository, environment, or organisation secret.",
    ),
    _r(
        "cron-trigger",
        r"\bcron\s*\(\s*['\"]([^'\"]+)['\"]",
        Category.REVIEW,
        "Cron trigger",
        "`on.schedule[].cron`.",
        "No `H` hash syntax; pick a fixed minute. Scheduled runs only fire on the default branch.",
    ),
    _r(
        "pollscm-trigger",
        r"\bpollSCM\s*\(",
        Category.DROP,
        "pollSCM trigger",
        "None needed; `on: push` and `on: pull_request` are event-driven.",
    ),
    _r(
        "upstream-trigger",
        r"\bupstream\s*\(",
        Category.REVIEW,
        "Upstream job trigger",
        "`on: workflow_run` or `repository_dispatch`.",
    ),
    # --- gates, locks, flow control -------------------------------------------------------------
    _r(
        "input-gate",
        r"\binput\s+(message|id)\s*:|\binput\s*\(|\binput\s+['\"]",
        Category.MANUAL,
        "Manual input gate",
        "A GitHub environment with required reviewers on the deploying job.",
        "Reviewers are configured in repo settings, not the workflow. Decide which environment "
        "models each gate.",
    ),
    _r(
        "submitter",
        r"\bsubmitter\s*:",
        Category.MANUAL,
        "input submitter restriction",
        "Required reviewers on the environment.",
    ),
    _r(
        "lock",
        r"\block\s*\(",
        Category.REVIEW,
        "lock() resource",
        "`concurrency: { group: <resource>, cancel-in-progress: false }`.",
        "Concurrency keeps one pending run and cancels older pending ones; a lock queued all.",
    ),
    _r(
        "milestone",
        r"\bmilestone\b",
        Category.MANUAL,
        "milestone()",
        "None. `concurrency` orders runs but never skips an older one that already started.",
    ),
    _r(
        "disable-concurrent",
        r"\bdisableConcurrentBuilds\s*\(",
        Category.AUTO,
        "disableConcurrentBuilds()",
        "Workflow-level `concurrency:` group keyed on the ref.",
    ),
    _r(
        "timeout",
        r"\btimeout\s*\(",
        Category.AUTO,
        "timeout",
        "`timeout-minutes` on the job or step.",
        "A timeout wrapping `input` has no equivalent; pending deployments wait up to 30 days.",
    ),
    _r(
        "retry",
        r"\bretry\s*\(",
        Category.REVIEW,
        "retry()",
        "No built-in step retry. A shell loop or a marketplace retry action.",
    ),
    _r(
        "when-branch",
        r"\bbranch\s+['\"]([^'\"]+)['\"]",
        Category.AUTO,
        "when { branch }",
        "`if: github.ref == 'refs/heads/<name>'` or an `on.push.branches` filter.",
    ),
    _r(
        "when-expression",
        r"\bexpression\s*\{",
        Category.REVIEW,
        "when { expression }",
        "`if:` using the expression syntax.",
        "Groovy expressions must be rewritten; only `inputs.*`, `github.*`, `needs.*` "
        "and `env.*` are available.",
    ),
    _r(
        "when-changeset",
        r"\bchangeset\s+['\"]",
        Category.AUTO,
        "when { changeset }",
        "`on.push.paths` / `on.pull_request.paths` filters, or a paths-filter action.",
    ),
    # --- artifacts and reports --------------------------------------------------------------------
    _r(
        "stash",
        r"\b(stash|unstash)\s*[\(\s]",
        Category.AUTO,
        "stash / unstash",
        "`actions/upload-artifact` and `actions/download-artifact`, or a single job.",
    ),
    _r(
        "archive-artifacts",
        r"\barchiveArtifacts\b",
        Category.AUTO,
        "archiveArtifacts",
        "`actions/upload-artifact` with `retention-days`.",
        "`fingerprint:` has no equivalent.",
    ),
    _r(
        "junit",
        r"\bjunit\b",
        Category.REVIEW,
        "junit report publisher",
        "Upload the XML as an artifact; a test-reporter action for UI results.",
        "There is no UNSTABLE result; failing tests fail the job.",
    ),
    _r(
        "checkout-scm",
        r"\bcheckout\s+scm\b",
        Category.AUTO,
        "checkout scm",
        "`actions/checkout`.",
    ),
    # --- post -------------------------------------------------------------------------------------
    _r(
        "post-block",
        r"\bpost\s*\{",
        Category.AUTO,
        "post { } block",
        "A job with `needs` on everything and `if: always()` that inspects `needs.*.result`.",
        once=True,
    ),
    _r(
        "post-unstable",
        r"\bunstable\s*\{",
        Category.MANUAL,
        "post { unstable }",
        "None; UNSTABLE does not exist. Decide whether those cases are failures or successes.",
    ),
    _r(
        "clean-ws",
        r"\bcleanWs\s*\(",
        Category.DROP,
        "cleanWs()",
        "None; hosted runners are ephemeral. Self-hosted runners may need a cleanup step.",
    ),
    # --- options that just go away ----------------------------------------------------------------
    _r(
        "build-discarder",
        r"\bbuildDiscarder\s*\(",
        Category.DROP,
        "buildDiscarder / logRotator",
        "Repository log retention settings and `retention-days` on artifacts.",
    ),
    _r(
        "timestamps",
        r"\btimestamps\s*\(",
        Category.DROP,
        "timestamps()",
        "Always on.",
    ),
    _r(
        "ansi-color",
        r"\bansiColor\s*\(",
        Category.DROP,
        "ansiColor()",
        "Always on.",
    ),
    _r(
        "skip-default-checkout",
        r"\bskipDefaultCheckout\s*\(",
        Category.DROP,
        "skipDefaultCheckout()",
        "Jobs never check out implicitly; omit `actions/checkout`.",
    ),
    # --- plugin steps -----------------------------------------------------------------------------
    _r(
        "plugin-slack",
        r"\bslackSend\b",
        Category.REVIEW,
        "slackSend (Slack plugin)",
        "A Slack action (slackapi/slack-github-action) or curl to an incoming webhook.",
    ),
    _r(
        "plugin-email",
        r"\b(emailext|mail)\s*[\(\s]",
        Category.REVIEW,
        "emailext / mail",
        "GitHub's built-in failure notifications, or an SMTP marketplace action.",
    ),
    _r(
        "plugin-sonar",
        r"\bwithSonarQubeEnv\b|\bwaitForQualityGate\b",
        Category.REVIEW,
        "SonarQube plugin wrapper",
        "SonarSource/sonarqube-scan-action with SONAR_TOKEN and SONAR_HOST_URL secrets.",
    ),
    _r(
        "plugin-docker-global",
        r"\bdocker\.(build|image|withRegistry)\s*\(",
        Category.AUTO,
        "docker.* global variable (Docker Pipeline plugin)",
        "docker/login-action, docker/build-push-action.",
    ),
    _r(
        "plugin-git-publisher",
        r"\bgitPublisher\b|\bsshagent\s*\(",
        Category.REVIEW,
        "git push from pipeline",
        "GITHUB_TOKEN with `contents: write`, or a deploy key secret.",
    ),
    _r(
        "plugin-tools",
        r"\btools\s*\{",
        Category.AUTO,
        "tools { } block",
        "actions/setup-java, setup-go, setup-node, setup-python, etc.",
    ),
    # --- env vars ---------------------------------------------------------------------------------
    _r(
        "jenkins-env-var",
        r"\benv\.(BUILD_URL|BUILD_NUMBER|BUILD_ID|JOB_NAME|GIT_COMMIT|GIT_BRANCH|BRANCH_NAME|"
        r"CHANGE_ID|WORKSPACE|NODE_NAME|BUILD_TAG)\b",
        Category.AUTO,
        "Jenkins built-in env var",
        "github context: BUILD_URL -> run URL from github.server_url/repository/run_id; "
        "BUILD_NUMBER -> github.run_number; JOB_NAME -> github.workflow; GIT_COMMIT -> "
        "github.sha; BRANCH_NAME -> github.ref_name; "
        "CHANGE_ID -> github.event.pull_request.number; WORKSPACE -> github.workspace.",
    ),
]

# Names of steps that are plugin-provided or built-in; anything else called like a step and
# not defined in the pipeline itself is assumed to be a shared-library step.
KNOWN_STEPS: frozenset[str] = frozenset(
    {
        "sh",
        "bat",
        "powershell",
        "pwsh",
        "echo",
        "error",
        "sleep",
        "retry",
        "timeout",
        "checkout",
        "git",
        "stash",
        "unstash",
        "archiveArtifacts",
        "junit",
        "input",
        "lock",
        "milestone",
        "withCredentials",
        "withEnv",
        "dir",
        "script",
        "parallel",
        "stage",
        "steps",
        "post",
        "always",
        "success",
        "failure",
        "unstable",
        "changed",
        "aborted",
        "cleanup",
        "fixed",
        "regression",
        "pipeline",
        "agent",
        "options",
        "triggers",
        "parameters",
        "environment",
        "stages",
        "when",
        "tools",
        "matrix",
        "axes",
        "axis",
        "docker",
        "dockerfile",
        "node",
        "label",
        "any",
        "none",
        "kubernetes",
        "cron",
        "pollSCM",
        "upstream",
        "choice",
        "booleanParam",
        "string",
        "text",
        "password",
        "credentials",
        "expression",
        "branch",
        "allOf",
        "anyOf",
        "not",
        "buildingTag",
        "changeset",
        "changelog",
        "equals",
        "tag",
        "triggeredBy",
        "buildDiscarder",
        "logRotator",
        "disableConcurrentBuilds",
        "timestamps",
        "ansiColor",
        "skipDefaultCheckout",
        "skipStagesAfterUnstable",
        "quietPeriod",
        "slackSend",
        "emailext",
        "mail",
        "withSonarQubeEnv",
        "waitForQualityGate",
        "cleanWs",
        "deleteDir",
        "readFile",
        "writeFile",
        "fileExists",
        "readJSON",
        "writeJSON",
        "readYaml",
        "writeYaml",
        "httpRequest",
        "build",
        "catchError",
        "warnError",
        "waitUntil",
        "wrap",
        "withMaven",
        "withGradle",
        "usernamePassword",
        "file",
        "sshUserPrivateKey",
        "secretText",
        "culprits",
        "requestor",
        "developers",
        "sshagent",
        "gitPublisher",
        "pipelineTriggers",
        "properties",
        "library",
        "load",
        "container",
        "podTemplate",
        "containerTemplate",
        "publishHTML",
        "cobertura",
        "recordIssues",
        "step",
        "scm",
        "env",
        "params",
        "currentBuild",
        "return",
        "def",
        "if",
        "else",
        "for",
        "while",
        "try",
        "catch",
        "finally",
        "new",
        "throw",
        "println",
        "print",
        "map",
        "list",
        "set",
        "get",
        "put",
        "size",
        "each",
        "collect",
        "find",
        "take",
        "trim",
        "toLowerCase",
        "toUpperCase",
        "split",
        "join",
        "contains",
        "startsWith",
        "endsWith",
        "replace",
        "replaceAll",
        "format",
        "toString",
        "toInteger",
        "isEmpty",
        # Directive options and named arguments that appear at the start of a line inside
        # agent/options/parameters/plugin blocks; they look like `name 'value'` calls.
        "image",
        "args",
        "alwaysPull",
        "reuseNode",
        "customWorkspace",
        "registryUrl",
        "registryCredentialsId",
        "filename",
        "additionalBuildArgs",
        "yaml",
        "yamlFile",
        "defaultContainer",
        "inheritFrom",
        "cloud",
        "channel",
        "color",
        "message",
        "subject",
        "body",
        "recipientProviders",
        "url",
        "unit",
        "time",
        "resource",
        "inversePrecedence",
        "ok",
        "id",
        "name",
        "includes",
        "excludes",
        "artifacts",
        "fingerprint",
        "testResults",
        "allowEmptyResults",
        "returnStdout",
        "returnStatus",
        "credentialsId",
        "usernameVariable",
        "passwordVariable",
        "variable",
        "defaultValue",
        "description",
        "choices",
        "numToKeepStr",
        "daysToKeepStr",
        "artifactNumToKeepStr",
        "values",
        "abortPipeline",
        "activity",
        "quiet",
        "beforeAgent",
        "beforeInput",
        "beforeOptions",
    }
)

# Steps provided by plugins that are worth calling out by name in the report.
PLUGIN_STEPS: frozenset[str] = frozenset(
    {
        "slackSend",
        "emailext",
        "withSonarQubeEnv",
        "waitForQualityGate",
        "junit",
        "publishHTML",
        "cobertura",
        "recordIssues",
        "httpRequest",
        "withMaven",
        "withGradle",
        "sshagent",
        "gitPublisher",
        "kubernetes",
        "podTemplate",
        "ansiColor",
        "timestamps",
        "cleanWs",
    }
)
